name: Main CI

on:
  push:
    branches:
      - '**'
  pull_request:
    braches:
      - '**'

jobs:
  test-and-coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python -m pip install coverage
          cd tests
          python -m coverage run -m unittest
          python -m coverage lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: tests/coverage.lcov